# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 13772ff047e1973e75fd79d708c1af56775d253e06bd4efdfbfbcc6cb37772fc04b8cf5f734a58d073a38f751d95b4ce7c5daa47c6e8b4b4296a96a4460e2992

test:
  secret_key_base: a5289c6fd9408153f8f736755cb311997f70d9041e1ba1f678dae7c8b06f4ea5df2cda78a289785c8401babba3fce182b676ccfcd423855eb3382f3f65f62e4c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
